apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
stringData:
  username: "root"
  password: "your-secure-password-here"
  order-db-url: "mysql://root:your-secure-password-here@mysql-service:3306/orders_db"
