apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-service
  labels:
    app: kitchen-service
    tier: application
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kitchen-service
  template:
    metadata:
      labels:
        app: kitchen-service
        tier: application
    spec:
      containers:
      - name: kitchen-service
        image: php:8.2-apache
        ports:
        - containerPort: 80
          name: http
        env:
        - name: DB_HOST
          value: mysql-kitchen
        - name: DB_DATABASE
          value: kitchen_db
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: root
        - name: DELIVERY_SERVICE_URL
          value: http://delivery-service
        - name: REDIS_HOST
          value: redis
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: kitchen-service-code
          mountPath: /var/www/html
      volumes:
      - name: kitchen-service-code
        configMap:
          name: kitchen-service-config
